### PR TITLE
Make the script work again with the new Dropbox API. CAVEAT: the feat…

### PR DESCRIPTION
**Pull request by lmanul**
…ure where a file that didn't exist at that point in time would get deleted hasn't been restored yet. But given that the old Dropbox API isn't functional anymore, this makes the script work again for the most part.

### CODE REVIEW

**Comment by clark800** [comment]
Thanks! Is it harder to do deletions now? I'm worried that the script could be confusing without that functionality.

**Comment by lmanul** [comment]
I don't think it's harder, I just thought I would fix the "most urgent", since the script is basically useless as it is with the new API so this is better than the current state :-)

**Comment by clark800** [comment]
Ok, I'll leave this up until myself or someone has time to finish it up.

**Comment by lmanul** [comment]
Okay, no worries. I can try to do the deletion part too, shouldn't be much more work. I'll keep you posted. But anyone else reading this feel free ^^

**Comment by brianroach** [comment]
How would one restore the main Dropbox folder - simply the whole thing? I keep getting this when I try to restore with this updated version of the script:

```
briansmac:New Folder With Items anodigital$ python2.7 restore.py /home/user/dropbox 2017-09-26
Restoring folder: /home/user/dropbox
ApiError('2b9d7e9004a02812897eeeeb54a65e08', ListFolderError(u'path', LookupError(u'not_found', None)))
Note: You must specify the path starting with "/", where "/" is the root
of your dropbox folder. So if your dropbox directory is at "/home/user/dropbox"
and you want to restore "/home/user/dropbox/folder", the ROOTPATH is "/folder".

briansmac:New Folder With Items anodigital$
```

**Comment by lmanul** [comment]
Did you read the error message? :-) 

---
You must specify the path starting with "/", where "/" is the root
of your dropbox folder. So if your dropbox directory is at "/home/user/dropbox"
and you want to restore "/home/user/dropbox/folder", the ROOTPATH is "/folder".
---

So to restore the whole thing, I assume you need "/"

**Comment by brianroach** [comment]
@imanul - yeah, I did try that. In the bottom of my original post I wrote all the variations that I had tried and still received the same error message. :/

**Comment by mgenet** [comment]
You guys saved my evening!

**Comment by lmanul** [comment]
Glad to help :-)

**Comment by carltonmatthew** [comment]
Didn't work for me;
 python2.7 restore.py /Treasurer/SRPCDB 2018-08-22
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "restore.py", line 113, in <module>
    main()
  File "restore.py", line 108, in main
    client = login('token.dat')
  File "restore.py", line 41, in login
    access_token = authorize()
  File "restore.py", line 22, in authorize
    flow = dropbox.client.DropboxOAuth2FlowNoRedirect(APP_KEY, APP_SECRET)
AttributeError: 'module' object has no attribute 'client'
carlton@Dragon3Mint /mnt/FastData/DOWNLOADS/dropbox-restor

**Pull request closed without merging**
